export const PLAYER_ADD = 'PLAYER_ADD';
export const PLAYER_UPDATE = 'PLAYER_UPDATE';
export const ROUND_SCOPA_ADD = 'ROUND_SCOPA_ADD';
export const ROUND_SCOPA_POINT_ADD = 'ROUND_SCOPA_POINT_ADD';
export const ROUND_SCOPA_RESET = 'ROUND_SCOPA_RESET';
export const FIRST_PLAYER_ID_TO_SERVE_SET = 'FIRST_PLAYER_ID_TO_SERVE_SET';
